### PR TITLE
Patch 3

### LINKED ISSUE #101: Switch glide to go modules for dependency management
We should switch ~glide~ go modules to dep for vendors management. Kubernetes's staging packages should be handled carefully (e.g. refer scripts/update-dependencies.sh)

- [ ] Replace glide with ~dep~ go modules
- [ ] Update scripts/update-dependencies.sh
- [ ] Update docs dependency-management.md

/help

### PR DESCRIPTION
**Pull request by Abhik1998**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
kind bug
>
> /kind api-change
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Updatind using dep ,removing glide for go module management
**Which issue(s) this PR fixes**:

Fixes #101 

**Special notes for your reviewer**:
All conditions have been checked and the vendors folder has been updated

**Release note**:
```
action required=test

```

### CODE REVIEW

**Comment by feiskyer** [comment]
Could you rebase the commits to master and squash them? I think most files shouldn't be changed except the files under vendors and go module files.

**Comment by justaugustus** [comment]
/hold

Before we do anything else, we need to make a decision on whether we're moving to dep or go modules. There is parallel, conflicting work on #109.

@feiskyer @andyzhangx -- what are your thoughts?

**Comment by feiskyer** [comment]
Go modules is preferred, I have updated the title and conent in #101

**Comment by Abhik1998** [comment]
Okay then I am taking up that task
Go modules are preferred.

**Comment by justaugustus** [comment]
@Abhik1998 -- @jaybatra26 already appears to be working on that in #109. 
I'm going to close this PR out. Please continue the conversation on #109.

/close

**Pull request closed without merging**
