### PR TITLE
Use gomodules instead of glide for vendors management

### PR DESCRIPTION
**Pull request by jaybatra26**
Signed off by Jay Batra <jaybatra73@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by jaybatra26** [comment]
@feiskyer How can I imitate CI tests in local. Do I simply run `go test` or do I need to use scripts in tests folder. I tried `tests/k8s-azure/init.sh`. But it's throwing error for me `az command not found`

**Comment by feiskyer** [comment]
> How can I imitate CI tests in local. 

Run `make test-check` and `make test-unit`.

**Comment by jaybatra26** [comment]
@feiskyer I am getting 

`gopkg.in/alecthomas/gometalinter.v1
../../../pkg/mod/gopkg.in/alecthomas/gometalinter.v1@v1.2.1/main.go:129:69: cannot use loadConfig (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to kingpin.Flag("config", "Load JSON configuration from file.").Action
` 
when I run `make test-check`

**Comment by feiskyer** [comment]
Seems error because of dependencies conflicted. For a none clean Go path, you can just install via `go get gopkg.in/alecthomas/gometalinter.v1` (drop -u).

**Comment by jaybatra26** [comment]
@feiskyer Thanks.

**Comment by jaybatra26** [comment]
@feiskyer I am still facing the same error.

**Comment by feiskyer** [comment]
@jaybatra26 The go mod is not including all required packages.

The tricky thing is kubernetes manages some packages in its staging directory: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io. Those packages are used as symbol link in https://github.com/kubernetes/kubernetes/tree/master/vendor/k8s.io. 

in `hack/update-dependencies.sh`, glide-update-staging-mirror is tried to fix such issue. Could you try the same manner to include all required packages with go mod?

**Comment by justaugustus** [comment]
I _believe_ @liggitt tested porting kubernetes/kubernetes to go mod. Perhaps he can lend some suggestions here.

**Comment by liggitt** [comment]
my current efforts are in https://github.com/kubernetes/kubernetes/pull/74877 if you want to follow along

https://github.com/liggitt/kubernetes/blob/go-mod-cleanup/hack/update-vendor.sh is how I'm rebuilding the vendor tree for kubernetes/kubernetes

**Comment by feiskyer** [comment]
@liggitt thanks.

@jaybatra26 Would you like to continue the PR?

**Comment by jaybatra26** [comment]
Thanks @liggitt for a similar example. @feiskyer Yep, I will continue the PR. Will try to do it asap.

**Comment by Abhik1998** [comment]
@jaybatra26  use of the go.mod file is not suffice.We need to import that file to be used rather than the glide

**Comment by Abhik1998** [comment]
@jaybatra26  use of the go.mod file is not suffice.We need to import that file to be used rather than the glide.Moreover, you need to change the .yml file in the directory too. 

And as mentioned by @feiskyer  I used those packages and tried running he tests locally using 

> go test
and also installed ginkgo framework for testing operations

**Comment by feiskyer** [comment]
> @jaybatra26 use of the go.mod file is not suffice.We need to import that file to be used rather than the glide

Right, those packages should be vendored by `go mod vendor`

**Comment by feiskyer** [comment]
@jaybatra26  Any updates on this?

**Comment by feiskyer** [comment]
Close in favor of #142.

/close

**Pull request closed without merging**
