### PR TITLE
Removing translation dir

### PR DESCRIPTION
**Pull request by Abhik1998**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Removes an unnecessary folder and adds service annotation tests for load-balancer
**Which issue(s) this PR fixes**:

ref. #7 

**Special notes for your reviewer**:
none

**Release note**:
```
none
```

### CODE REVIEW

**Comment by feiskyer** [comment]
Actually, only translation dir is deleted in this PR, but the test case is not included. could you rename the PR title?

**Comment by Abhik1998** [comment]
Sir, going to add tests also in this PR

**Pull request merged**
