### PR TITLE
fix: Allow IMAGE_TAG to be overridden

### PR DESCRIPTION
**Pull request by jchauncey**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Allows the user to override the IMAGE_TAG value in the Makefile. This is useful when building ccm in a CI environment.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Allow user to override the IMAGE_TAG var in the Makefile
```

### CODE REVIEW

**Comment by jchauncey** [comment]
cc @ritazh @feiskyer 

This is so we can build the MCR image in CI and specify the tag at build time.

**Comment by feiskyer** [comment]
e2e is failing because of https://github.com/kubernetes/test-infra/pull/11887, let's get this in first since the e2e fixes would spend much more time

**Pull request merged**
