### PR TITLE
Make autoscaler e2e test more stable

### PR DESCRIPTION
**Pull request by fseldow**
**Which issue(s) this PR fixes**:
Autoscaler e2e test exceeds time or returns 'Unexpected EOF' error

```release-note
NONE
```

### CODE REVIEW

**Comment by fseldow** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify.  Thanks.

re-verify

**Comment by feiskyer** [comment]
The failing case is `CSI volume limit information using mock driver should report attach limit when limit is bigger than 0`.

@andyzhangx Since this is actually a mock CSI, should we pre-setup something for the test?

**Comment by feiskyer** [comment]
@fseldow pull-cloud-provider-azure-e2e is still flaky.  We have made it as optional now. Could you close this PR and open a new one?

**Pull request closed without merging**
