### PR TITLE
Build binaries with bazel

### LINKED ISSUE #102: Build binaries with Bazel
- [ ] Add bazel support
- [ ] Add auto-generation scritps
- [ ] Add documention

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Add support for bazel.

**Which issue(s) this PR fixes**:

Fixes #102 

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by nilo19** [comment]
> @nilo19 @feiskyer -- The [test failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/cloud-provider-azure/220/pull-cloud-provider-azure-e2e-ccm/1166172006001938432/) is a real one:
> 
> ```
> error creating cluster: could not ensure resource group: resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LocationRequired" Message="The location property is required for this definition."
> ```
> 
> Looks like the test definition/config is missing a location for the resource group.

Hi justaugustus, do you think https://github.com/kubernetes/test-infra/pull/14066 will solve this issue?

**Comment by feiskyer** [comment]
https://github.com/kubernetes/test-infra/pull/14066 would solve the issue, we are waiting for the new kubekins-e2e image bumping (probably tomorrow).

**Pull request merged**
