### PR TITLE
Update api version of azure sdk for go to 2018-07-01

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind api-change

> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by nilo19** [comment]
> Can we bump to 2018-08-01 to match this: [kubernetes/kubernetes#79583](https://github.com/kubernetes/kubernetes/pull/79583)

We use version 1.15 in our vendor thus 2018-07-01 is the latest version. Maybe we can try to upgrade it later.

**Comment by justaugustus** [comment]
> We use version 1.15 in our vendor thus 2018-07-01 is the latest version. Maybe we can try to upgrade it later.

Ahhh, right. Thanks @nilo19!

**Pull request merged**
