### PR TITLE
Upgrade kubernetes version to V1.14.0 beta.1

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

First step of #93: Upgrade kubernetes version to V1.14.0 beta.1.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Upgrade kubernetes version to V1.14.0 beta.1
```

### CODE REVIEW

**Comment by feiskyer** [comment]
e2e tests with error `Waiting up to 30m0s for all (but 0) nodes to be schedulable`.

@ritazh Have you observed same errors recently?

**Comment by ritazh** [comment]
@feiskyer I will look into this.

**Comment by ritazh** [comment]
@feiskyer Can you give `1.14.0-alpha.1` a try since `1.14.0-beta.1` is not in aks-engine v0.31.2 yet.
https://github.com/Azure/aks-engine/blob/v0.31.2/pkg/api/common/versions.go#L109

**Comment by feiskyer** [comment]
@ritazh Also found other issues because of version upgrade. Would fix and push later.

**Comment by feiskyer** [comment]
CI green now.

@andyzhangx  PTAL

**Pull request merged**
