### PR TITLE
Add support of testing standard LB and fix e2e docs

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind documentation

**What this PR does / why we need it**:

Add support of testing standard LB and fix e2e docs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Add support of testing standard LB and fix e2e docs
```

### CODE REVIEW

**Comment by justaugustus** [comment]
@feiskyer -- is there a good reason to not just make the default SKU Standard instead?

**Comment by feiskyer** [comment]
> @feiskyer -- is there a good reason to not just make the default SKU Standard instead?

Both standard and basic are supported today, and actually most customers are using basic SKU today.

**Pull request merged**
