### PR TITLE
removed files that caused 404s and reflected refactored links

### LINKED ISSUE #244: Stale information contained in cloud-controller-manager.md
Hi all,
https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/cloud-controller-manager.md
contains stale information, particularly in `Deploy AzureDisk CSI plugin` section
, as the master branch has diverged from the information contained therein (when it comes to rbac files especially).

This will lead to 404s - I am creating a fast PR to resolve this

### PR DESCRIPTION
**Pull request by thanasisk**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fixes documentation, especially in an area that the end user is supposed to practically copy and paste.
**Which issue(s) this PR fixes**:
Fixes #244 

**Special notes for your reviewer**:

**Release note**:
```
fixed outdated/invalid links in the documentation
```

### CODE REVIEW

**Comment by thanasisk** [comment]
I signed it!

**Comment by andyzhangx** [comment]
/test pull-cloud-provider-azure-e2e-ccm

> I signed it!

Hi @thanasisk , are you using azure disk csi driver recently?

**Comment by thanasisk** [comment]
Hi @andyzhangx 
I found the 404s as part of my prep work in order to use this. Does that answer your question?

**Comment by andyzhangx** [comment]
> Hi @andyzhangx
> I found the 404s as part of my prep work in order to use this. Does that answer your question?

thanks, let me know if you have issue about the azure csi driver.

**Comment by thanasisk** [comment]
I kind of messed up my git history. Do you mind if I close this PR and open an identical one with the CLA issue fixed?

**Pull request closed without merging**
