### PR TITLE
docs/cloud-provider-config.md: fix typo

### PR DESCRIPTION
**Pull request by invidian**
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR just fixes typo in documentation.
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by invidian** [comment]
CCLA signed.

**Comment by rata** [comment]
I've added the ok to test, as this seems safe to test :)

**Comment by feiskyer** [comment]
Thanks for the fix.
/lgtm
/release-note-none

**Pull request merged**
